version: 2
updates:
  # Enable version updates for git submodules
  - package-ecosystem: "gitsubmodule"
    # Look for `.gitmodules` in the `root` directory
    directory: "/"
    # Check the submodules for updates every month
    schedule:
      interval: "monthly"
